name: Snowflake Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SnowSQL CLI
      run: |
        curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.20-linux_x86_64.bash
        chmod +x snowsql-1.2.20-linux_x86_64.bash
        ./snowsql-1.2.20-linux_x86_64.bash

    - name: Build and deploy
      env:
        SNOWSQL_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
        SNOWSQL_USER: ${{ secrets.SNOWFLAKE_USER }}
        SNOWSQL_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      run: |
        snowsql -c myaccount -u myuser -d mydb -s myschema -f myscript.sql
